### ISSUE TITLE
In mixed faction shared army ai armies, only one commander is used

### ISSUE THREAD

**Issue by Stuart1998** [Quitch/Queller-AI#55]
Tested with a team of two bronze quellers on Lock. One com may build some pgens or mexes, but won't build a factory. Issue did not occur in 5v5 with Uber AIs (3MLA2Legionvs2MLA3Legion) on Clutch of Annihilation, although both teams built more vanilla than legion.

**Comment by Quitch** [comment]
This was unshared? Which slots was the ai using and which slot was which faction?

**Comment by Quitch** [comment]
Also you said one com may. Which one?

**Comment by Stuart1998** [comment]
This was shared, as it says in the title.

The idle com was the Legion com.

**Comment by Quitch** [comment]
Given shared ai armies are not natively supported you will need to provide the modifications you are running

**Comment by Quitch** [comment]
You will also need to provide the other information requested

**Comment by Stuart1998** [comment]
Three teams. Slot 1 and three were vanilla, slot two e was the mixed team. Commander order shouldn't matter given that both spawn in the same place.

This was the modification used: https://forums.uberent.com/threads/patch-shared-armies-for-ai-teams.70450/

**Comment by Quitch** [comment]
Ah yes, "shouldn't matter", in the same way that this _should work_

What was the Commander order, if you remember?

**Comment by Stuart1998** [comment]
I think vanilla and legion?

**Comment by Quitch** [comment]
Unable to replicate.
