### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by chaoszone** [Quitch/Queller-AI#56]
Does Queller AI support multi threading?
We love to play against AI but we always run into performance issues in the late game.

I read in the latest PA patch notes that AI should now support it but does this also apply to Queller AI?

**Comment by Quitch** [comment]
Please direct queries to the [Queller forum thread](https://forums.uberent.com/threads/rel-server-queller-ai-v4-0-com-pa-quitch-qquellerai.65795/). Issues should be used only for bug reporting.
